definitions:
  oms.OrderForSwag:
    properties:
      account:
        type: string
      avg_px:
        type: string
      clord_id:
        type: string
      closed:
        type: string
      id:
        type: integer
      maturity_day:
        type: integer
      maturity_month_year:
        type: string
      open:
        type: string
      ord_type:
        type: string
      order_id:
        type: string
      price:
        type: string
      put_or_call:
        type: string
      quantity:
        type: string
      security_desc:
        type: string
      security_type:
        type: string
      session_id:
        type: string
      side:
        type: string
      stop_price:
        type: string
      strike_price:
        type: string
      symbol:
        type: string
    type: object
info:
  contact: {}
  termsOfService: http://somewhere.com/
  title: Traderui API
  version: "1.0"
paths:
  /orders:
    get:
      description: get all order
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/oms.OrderForSwag'
            type: array
      summary: getOrders
    post:
      description: send 1 order
      produces:
      - application/json
      responses:
        "200":
          description: send 1 order
          schema:
            type: string
      summary: newOrder
schemes:
- https
- http
swagger: "2.0"
